name: Git Actions Demo
    - description:'Hello Everyone'
    - default:'Good Afternoon'
    - required:true

on: [push]

env:
  app_name: C00l_4PP.exe

jobs:
  actions_demo:
    runs-on: ubuntu-latest
    steps:
    - run: sleep 10
    - run: echo "Purvi"
    - run: touch github.txt
    - run: echo "github
                - users:- 90 million
                - launched:- April_10_2008
                - written_in:- Ruby, JavaScript, Go, C
                - parent_company:- Microsoft
                - employees:- 2500
                - revenue:- $1 Billion
                - hq:- SanFrancisco, California, US
                - type:- Collaborative Version control" >> github.txt
    - run: cat github.txt
    - run: ls -a
    - run: pwd
    - run: echo "$USER"
    - run: git clone https://github.com/ThakkarPurvi/QA-DevOpsApp
    - run: cat QA-DevOpsApp/README.md

  better_action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # Checking out and using the repo assigned to this workflow
    - run: chmod +x script.sh # Granting permission access to our script
    - run: ./script.sh # Running our script
    - run: echo $app_name

  exercise_action:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
      - run: echo "Pooh"
      - run: touch sum.py
      - run: |
          cat >>sum.py <<EOF
          no = list(map(int, input().split()))
          def no_sum():
            print(no)
            res = 0
            for i in no:
              res = res + i
              print(res)
          no_sum()
          EOF
      - run: cat sum.py
      - run: ls -a
      - run: pwd

  check_action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # Checking out and using the repo assigned to this workflow
    - run: chmod +x script.sh # Granting permission access to our script
    - run: ./script.sh # Running our script

  environment_variable_job:
    runs-on: ubuntu-latest
    env:
      name: Purvi
    steps:
      - run: echo "GitHub"
      - run: echo "Hello $name"
      - run: echo $app_name
      - run: echo "${{secrets.SECRET_PASSWORD}}"

